### ISSUE TITLE
Add interesting c++ patterns

### ISSUE THREAD

**Issue by Andyy-18** [Andyy-18/CPP-BASICS#1]

**Comment by suresh37** [comment]
I have added pascal's triangle (pattern program) in PR. please check and merge if it is fine for you.

**Comment by Andyy-18** [comment]
@sbhmrj bro.
See the issue and PR accordingly.

**Comment by priyanshuanand166** [comment]
Assign this to me as i am well versed in dsa and i am pretty confident that you will like my merge request.

**Comment by Andyy-18** [comment]
@priyanshuanand166 Go ahead.

**Comment by priyanshuanand166** [comment]
@Andyy-18 
Created PR #13 
Kindly review it.

**Comment by priyanshuanand166** [comment]
@Andyy-18 
Created PR #14 
Kindly review it.

**Comment by priyanshuanand166** [comment]
@Andyy-18 
Created PR #16 
Created PR #17 
Created PR #18 
Created PR #19 
Created PR #20 
Created PR #21 
Created PR #22 
Kindly review it.
