### ISSUE TITLE
Palindrome Linked List in CPP

### ISSUE THREAD

**Issue by harshita9621** [Andyy-18/CPP-BASICS#12]

**Comment by harshita9621** [comment]
@Andyy-18 Can I work on this

**Comment by Andyy-18** [comment]
@harshita9621 Go ahead.

**Comment by harshita9621** [comment]
@Andyy-18 Is this repo excluded from hacktoberfest or not.

**Comment by Andyy-18** [comment]
@harshita9621 My all contributors are in Waiting in the Hacktoberfest profile. 
So I'm not sure but I think it's not Hacktoberfest excluded.

**Comment by Pallab00122** [comment]
Please assign me the task

**Comment by Andyy-18** [comment]
@Pallab00122 Go ahead.
