### ISSUE TITLE
Add some Leetcode problems on CPP

### ISSUE THREAD

**Issue by Andyy-18** [Andyy-18/CPP-BASICS#32]

**Comment by dakshsinghrathore** [comment]
Hi there! Can you please assign it to me ??

**Comment by Andyy-18** [comment]
> Hi there! Can you please assign it to me ??

Go ahead.

**Comment by aadionweb07** [comment]
we have to add new questions for leetcode or we have to solve 
and can you please assign me??

**Comment by Andyy-18** [comment]
@aadionweb07 Add some good leetcode solved questions.

**Comment by harshil-1402** [comment]
can you assign it to me I want to contribute

**Comment by ZeeshanK07** [comment]
Hi! @Andyy-18, I have contributed a code on this programme. Please review #32 once.

**Comment by kushagra10bansal** [comment]
Hey! @Andyy-18 , i would love to contribute, could you please assign it to me?

**Comment by abhi87374** [comment]
kindly assign this to me...

**Comment by kushagra10bansal** [comment]
Hey! @Andyy-18, i have contributed a code. Please review once #56 . Thank you!

**Comment by Avra04** [comment]
Hi !! Andy ... Aniruddha here !! please assign this to me !!

**Comment by kushagra10bansal** [comment]
hey! @Andyy-18 . The label you've used for this issue is 'hactober'. I just wanted to confirm if it is accepted by the hacktober community or it has to be 'hac**k**tober'.

**Comment by Andyy-18** [comment]
@kushagra10bansal Two contributors got accepted by Hacktoberfest. 
So i think it has no problem. 

Actually this repo have hacktoberfest tag.
So no problem.

**Comment by harshiitsingh** [comment]
Hey @Andyy-18, please assign this issue to me.

**Comment by Shreya111111** [comment]
@Andyy-18  plz assign the task to me

**Comment by Sayan1412** [comment]
@Andyy-18 please can you assign this task to me

**Comment by KrishKumar3004** [comment]
Hi there! Can you please assign it to me ??

**Comment by super-duper-sp** [comment]
Hey, I would like to contribute. Please assign it to me.

**Comment by Ambuj1729** [comment]
Hi andy I want to contribute to your repo .Please assign it to me.

**Comment by jahnavimehta** [comment]
Hello! I would like to contribute. please could you assign this to me?

**Comment by guneet-01** [comment]
Hello @Andyy-18, please assign this issue to me.

**Comment by jahnavimehta** [comment]
Hello! @Andyy-18 I've added problem no. 328 from leetcode. Question is based on odd even linked list.  Please could you review it and let me know if any changes are required?
